package com.app.rupyz.custom_view.type

enum class FormItemType(val value: String) {
    SHORT_ANSWER("SHORT_ANSWER"),
    LONG_ANSWER("LONG_ANSWER"),
    DATE_PICKER("DATE_PICKER"),
    DATE_TIME_PICKER("DATE_TIME_PICKER"),
    DROPDOWN("DROPDOWN"),
    FILE_UPLOAD("FILE_UPLOAD"),
    MOBILE_NUMBER("MOBILE_NUMBER"),
    EMAIL_ADDRESS("EMAIL_ADDRESS"),
    ALPHABETS("ALPHABETS"),
    NUMBERS("NUMBERS"),
    DECIMAL("DECIMAL"),
    MULTIPLE_CHOICE("MULTIPLE_CHOICE"),
    CHECKBOX("CHECKBOX"),
    URL_INPUT("URL_INPUT"),
    RATING("RATING")
}