name: AndroidDemoForUATOnly

on:
  workflow_dispatch:
 ## push:
   ## branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('*/.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build AAB for release
        run: ./gradlew bundleuatRelease

      - name: Upload AAB to Slack
        run: |
          curl -F file=@./app/build/outputs/bundle/uatRelease/app-uat-release.aab \
               -F channels=C0769K07NNS \
               -F token=$SLACK_TOKEN \
               https://slack.com/api/files.upload
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
