name: AndroidDemoForUATOnly

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create File
        run: echo "Hello, world!" > hello.txt

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Upload File to S3
        run: |
          aws s3 cp hello.txt s3://mybuckethaibnade/
          echo "AAB file uploaded to S3"
          
      - name: Send Notification to Microsoft Teams
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          AAB_URL="https://${S3_BUCKET_NAME}.s3.${AWS_REGION}.amazonaws.com/builds/hello.txt"
          curl -H 'Content-Type: application/json' -d "{
            \"text\": \"A new Android App Bundle is available: <${AAB_URL}|Download>\"
          }" $TEAMS_WEBHOOK_URL
