name: AndroidDemoForUATOnly

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('*/.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build AAB for release
        run: ./gradlew bundleuatRelease

      - name: Upload Aab-bundle as artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-bundle
          path: ./app/build/outputs/bundle/uatRelease

      - name: Download AAB artifact
        uses: actions/download-artifact@v2
        with:
          name: my-app-aab
          path: /tmp/aab

      - name: Send AAB to Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # Or your Slack access token
        run: |
          curl -X POST -F file=@/tmp/aab/app-uat-release.aab -F channels=C0769JXDSJ2 -F token=$SLACK_WEBHOOK_URL https://slack.com/api/files.upload  
