name: FileMove
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Create File
        run: sudo apt install curl
        
      - name: Create File
        run: echo "Hello, world!" > test.txt

      - name: Store File as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-file
          path: test.txt

      - name: Download File Artifact
        uses: actions/download-artifact@v2
        with:
          name: my-file
          path: /tmp

      - name: Upload AAB to Teams
        run: |
          curl -X POST -H 'Content-Type: application/json' -d '{
            "text": "New AAB file generated!",
            "attachments": [
              {
                "title": "AAB File",
                "text": "The AAB file has been uploaded.",
                "color": "#0078D7",
                "actions": [
                  {
                    "name": "Download",
                    "type": "openUrl",
                    "targets": [
                      {
                        "os": "default",
                        "uri": "https://example.com/path/to/aab_file.aab"
                      }
                    ]
                  }
                ]
              }
            ]
          }' ${{ secrets.TEAMS_WEBHOOK_URL }}
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}


