name: AndroidDemoForUATOnly

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Create File
        run: sudo apt install curl
        
      - name: Create File
        run: echo "Hello, world!" > test.txt

      - name: Store File as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-file
          path: test.txt

      - name: Download File Artifact
        uses: actions/download-artifact@v2
        with:
          name: my-file
          path: /tmp

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          SOURCE_DIR: '/tmp'  # Adjust this to your build output directory
          AWS_REGION: 'ap-southeast-2'  # Adjust to your S3 bucket region
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}  # Add your bucket name to GitHub Secrets
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


