name: AndroidDemoForUATOnly

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('*/.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build AAB for release
        run: |
          IST_DATE=$(TZ="Asia/Kolkata" date '+%Y%m%d_%H%M%S')
          ./gradlew bundleuatRelease
          mv ./app/build/outputs/bundle/uatRelease/app-uat-release.aab ./app/build/outputs/bundle/uatRelease/app-uat-release-${IST_DATE}.aab

      - name: Upload AAB to Teams
        run: |
          curl -X POST -H 'Content-Type: application/json' -d '{
            "text": "New AAB file generated!",
            "attachments": [
              {
                "title": "AAB File",
                "text": "The AAB file has been uploaded.",
                "color": "#0078D7",
                "actions": [
                  {
                    "name": "Download",
                    "type": "openUrl",
                    "targets": [
                      {
                        "os": "default",
                        "uri": "https://rupyz-my.sharepoint.com/:f:/r/personal/vikramsingh_rathor_rupyz_com/Documents/Apps?csf=1&web=1&e=88KgcW"
                      }
                    ]
                  }
                ]
              }
            ]
          }' ${{ secrets.TEAMS_WEBHOOK_URL }}
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks
        env:
          SOURCE_DIR: './app/build/outputs/bundle/uatRelease' 
          AWS_REGION: 'ap-southeast-2' 
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}  
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
