name: AndroidDemoForUATOnly

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create File
        run: echo "Hello, world!" > hello.txt

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Upload File to S3
        run: |
          aws s3 cp hello.txt s3://mybuckethaibnade/hello.txt --acl public-read
          echo "AAB file uploaded to S3"
          
      - name: Generate Public URL
        id: get-url
        run: |
          URL=$(aws s3 presign s3://your-bucket-name/hello.txt --expires-in 3600)
          echo "::set-output name=url::$URL"

      - name: Post URL to Teams
        run: |
          curl -X POST -H 'Content-Type: application/json' -d '{
            "text": "Download the file from S3: ${{ steps.get-url.outputs.url }}"
          }' ${{ secrets.TEAMS_WEBHOOK_URL }}
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
