name: Build DEV APK

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  build_apk:
    name: Build APK
    #if: github.event.pull_request.merged
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('*/.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build APK for release
        run:  ./gradlew assembleDevRelease

      - name: Generate Timestamp for APK
        id: timestamp-apk
        run: echo "::set-output name=timestamp::$(date +'%Y%m%d%H%M%S')"

      - name: Extract Custom Variable for APK
        id: extract-variable-apk
        run: |
          CUSTOM_VARIABLE=$(awk -F "\"" '/versionName/ {print $2}' app/build.gradle)
          echo "::set-output name=custom-variable-apk::$CUSTOM_VARIABLE"

      - name: Rename APK with Timestamp
        run: mv ./app/build/outputs/apk/dev/release/devRelease* "./app/build/outputs/apk/dev/release/app-dev-release_${{ steps.extract-variable-apk.outputs.custom-variable-apk }}_${{ steps.timestamp-apk.outputs.timestamp }}.apk"
    
      - name: Configure AWS Credentials for APK
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Install AWS CLI for APK
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Upload APK to S3
        run: |
          aws s3 cp ./app/build/outputs/apk/dev/release/app-dev-release_${{ steps.extract-variable-apk.outputs.custom-variable-apk }}_${{ steps.timestamp-apk.outputs.timestamp }}.apk s3://${{ secrets.AWS_S3_BUCKET }}/APK/

      - name: Generate Public URL for APK
        id: get-url-apk
        run: |
          URL=$(aws s3 presign s3://${{ secrets.AWS_S3_BUCKET }}/APK/app-dev-release_${{ steps.extract-variable-apk.outputs.custom-variable-apk }}_${{ steps.timestamp-apk.outputs.timestamp }}.apk --expires-in 432000 --region ${{ secrets.AWS_REGION }} --endpoint-url https://s3.${{ secrets.AWS_REGION }}.amazonaws.com)
          echo "::set-output name=url-apk::$URL"

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh
          
      - name: Fetch PR Details
        run: |
          PR_BODY=$(gh pr view ${{ github.event.pull_request.number }} --json body --jq '.body')
          ESCAPED_BODY=$(echo "$PR_BODY" | sed -e 's/\r//g' -e 's/\n/\\n/g' -e 's/"/\\"/g')
          echo "PR_BODY=${ESCAPED_BODY}" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Post APK URL to Slack1
        run: |
          curl -X POST -H 'Content-Type: application/json' -d "{
            \"text\": \"${PR_BODY}\nDownload the APK file for UAT using version ${{ steps.extract-variable-apk.outputs.custom-variable-apk }}: <${{ steps.get-url-apk.outputs.url-apk }}|Click Here>\"
          }" $SLACK_WEBHOOK_URL
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          PR_BODY: ${{ env.PR_BODY }}

      - name: Post Failure Notification to Slack for APK
        if: ${{ failure() }}
        run: |
          curl -X POST -H 'Content-Type: application/json' -d '{
            "text": "Build failed for APK! Please check the workflow for details."
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
