name: Create File and Notify Slack with PR Comment

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  fetch_comment_and_notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Fetch Latest PR Comment
        id: fetch-latest-comment
        run: |
          gh auth login --with-token <<< "${{ secrets.GH_TOKEN }}"
          LATEST_COMMENT=$(gh pr view ${{ github.event.pull_request.number }} --json comments --jq '.comments[-1].body')
          ESCAPED_COMMENT=$(echo "$LATEST_COMMENT" | sed -e 's/\r//g' -e 's/\n/\\n/g' -e 's/"/\\"/g')
          echo "LATEST_COMMENT=${ESCAPED_COMMENT}" >> $GITHUB_ENV

      - name: Write Comment to File
        run: |
          echo "${{ env.LATEST_COMMENT }}" > pr_comment.txt
          cat pr_comment.txt  # Output the comment to the console

      - name: Send Notification to Slack
        run: |
          curl -X POST -H 'Content-Type: application/json' -d '{
            "text": "Latest PR Comment: \n${{ env.LATEST_COMMENT }}"
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
