name: Create File and Notify Slack with PR Comment

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  fetch_comment_and_notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Fetch PR Details
        run: |
          PR_BODY=$(gh pr view ${{ github.event.pull_request.number }} --json body --jq '.body')
          ESCAPED_BODY=$(echo "$PR_BODY" | awk '{gsub(/[\r\n]/,"\\n")}1' | sed -e 's/"/\\"/g')
          echo "PR_BODY=\"$ESCAPED_BODY\"" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Post PR Comment to Slack
        run: |
          curl -X POST -H 'Content-Type: application/json' -d "{
            \"text\": \"${PR_BODY}\nDownload the AAB file version ${{ steps.extract-variable.outputs.custom-variable }}: <${{ steps.get-url.outputs.url }}|Click Here>\"
          }" $SLACK_WEBHOOK_URL
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Post Failure Notification to Slack for AAB
        if: ${{ failure() }}
        run: |
          curl -X POST -H 'Content-Type: application/json' -d '{
            "text": "Build failed for AAB! Please check the workflow for details."
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Write Comment to File
        run: |
          echo "${PR_BODY}" > pr_comment.txt
          cat pr_comment.txt  # Output the comment to the console
